In [4]:
import numpy as np

In [5]:
# Input: Pack Vertices into One Matrix

R = np.array([
    [0, -1],
    [1, 0]
])

In [9]:
P = np.array([
    [1, 3, 2],
    [1, 1, 2]
])

In [10]:
# Calculation: One Operation Transforms all Points

# The @ symbol is pythons operator for matrix multiplication

P_transformed = R @ P

In [11]:
print(P)

[[1 3 2]
 [1 1 2]]


In [12]:
print(P_transformed)

[[-1 -1 -2]
 [ 1  3  2]]
