In [ ]:
# Notebooks - a notebook is a special file (usually ,ipynb) that lets you:
# write Code
# run Code
# see output 
# Add notes equations, images, charts - all in one place



#Numpy - It is a numeric libray of python to make possible arrays in python
# Numpy is written in c which are compiled and super fast.
# this is the main reason numpy is upto 50x faster than python list.

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1,2,3.5]
a

[1, 2, 3.5]

In [5]:
np.array(a) #convert every value of a into float datatype

array([1. , 2. , 3.5])

In [6]:
l = [[1,2,3],[1,2,3],[1,2,3]]
l

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [11]:
np.array([[1,2,3],[1,2,3],[1,2,3]])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [19]:
# Array generation function

arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr2 = np.arange(1,11,2)
arr2

array([1, 3, 5, 7, 9])

In [23]:
arr = np.zeros((4,7))
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [26]:
arr = np.ones((6,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [33]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [ ]:
# Random Number Generation

arr = np.random.rand(10)
arr


# All values comes within a range of 0 to 1 this is a concept of normalization in statistics
# and when it came in range of 3 to -3 then it is standardization

array([0.48672808, 0.26680591, 0.04469299, 0.65491445, 0.89980549,
       0.78196527, 0.39680021, 0.19831857, 0.17199079, 0.50323797])

In [ ]:
arr = np.random.randn(10)     #it came in range of 3 to -3 then it is standardization
arr

array([-0.72909061, -0.29035108,  1.5328432 ,  0.93308839,  0.07582537,
        0.85704019, -0.78943836,  1.29223051,  2.25230235,  1.29502551])

In [9]:
arr = np.random.randint(10,20,12)
arr

array([14, 15, 17, 17, 15, 18, 18, 17, 14, 19, 16, 12], dtype=int32)

In [11]:
# Array Attributes

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr.shape

(3, 3)

In [13]:
arr.size

9

In [14]:
arr.dtype

dtype('int64')

In [16]:
# Array Methods

arr.min()

np.int64(1)

In [17]:
arr.max()

np.int64(9)

In [18]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0)  # it provides us the sum of column wise axis to get we use 0f

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1) # it provides us with the sum of row wise to get this we use 1 in axis

array([ 6, 15, 24])

In [22]:
arr.mean()

np.float64(5.0)

In [23]:
arr.std()

np.float64(2.581988897471611)

In [24]:
arr.argmax()

np.int64(8)

In [25]:
arr.argmin()

np.int64(0)

In [30]:
# Reshaping and resizing

arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
arr.reshape(3,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [37]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [40]:
arr = np.arange(1,41)
arr.reshape(8,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [43]:
# numpy indexing and slicing of vectors

arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# indexing
arr[6]

np.int64(17)

In [ ]:
# slicing
arr[1:5]

array([12, 13, 14, 15])

In [51]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
arr[4:]

array([15, 16, 17, 18, 19, 20])

In [56]:
arr[3::]

array([14, 15, 16, 17, 18, 19, 20])

In [61]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [65]:
# Numpy indexing and slicing of matrix

arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [67]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[2][3]

np.int64(14)

In [77]:
arr[0,4]

np.int64(5)

In [78]:
arr[[0,1],[2,3]]

array([3, 9])

In [79]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [81]:
arr[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [82]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [88]:
arr[3::2,3:]

array([[19, 20],
       [29, 30]])

In [100]:
# Boolean indexing

arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [101]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [102]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [105]:
# Numpy Array Operations

# Arithmetic Operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [106]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [107]:
a2 - a1

array([5, 5, 5, 5, 5])

In [110]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [111]:
a2 * a1

array([ 6, 14, 24, 36, 50])

In [112]:
a2 / a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [115]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [113]:
a2 // a1

array([6, 3, 2, 2, 2])

In [116]:
a1 // a2

array([0, 0, 0, 0, 0])

In [114]:
a2 % a1

array([0, 1, 2, 1, 0])

In [117]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [118]:
a2 ** a1

array([     6,     49,    512,   6561, 100000])

In [ ]:
# Broadcasting - refers to performing operations to all the elemens of the array

l = [10,20,30,40]
arr = np.array(l)

In [120]:
arr + 10

array([20, 30, 40, 50])

In [123]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [124]:
arr + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [133]:
# Deep and shalow copy 

# shalow copy - refers to something like we have a array a took a slice out of it and performing operations over it that does not applies over the main array

a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [130]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [134]:
# Deep copy - refers to something like we have a array a took a slice out of it and performing operations over it that does applies over the main array Also.

a 
b = a

In [135]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a # Changes are too applied to the a also this is a example of deep copy


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [145]:
# Another example of shallow copy

a = np.arange(1,21)
b = a.copy()

In [146]:
b[0] = 99

In [147]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [148]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [149]:
# Matrix Operations

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [150]:
A

array([[1, 2],
       [3, 4]])

In [151]:
B

array([[5, 6],
       [7, 8]])

In [153]:
A @ B

array([[19, 22],
       [43, 50]])

In [155]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [156]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [157]:
A.T

array([[1, 3],
       [2, 4]])

In [158]:
B.T

array([[5, 7],
       [6, 8]])

In [159]:
# Advance Array Manipulation

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [160]:
# Stacking Array

# We can not stack two Matrix so we have to go for vertors/array

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [161]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [162]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [164]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [166]:
# Splitting Array

c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [167]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [170]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [176]:
a = np.vsplit(c,2)
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [177]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [28]:
# Numpy Excercises

# Ex 1 - Valid Suduko

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [29]:
np.shape(s)

(9, 9)

In [30]:
b = np.sum(s,axis=1)

In [31]:
b[ b == 45]

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
for i in b:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
    print("For Rows it is valid")

For Rows it is valid


In [35]:
c = np.sum(s,axis=0)

In [36]:
for i in c:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
    print("For columns it is valid")

For columns it is valid


In [56]:
checksum = s[:3,:3]
checksum

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [55]:
np.sum(checksum)

np.int64(45)

In [69]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [150]:
# General Questions

import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [151]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [152]:
#Find the average age of students.
np.mean(data[:,0])


np.float64(18.4)

In [153]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [154]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [155]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [156]:
#Increase Math marks of all students by 5.
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [157]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [158]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [159]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [160]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])