In [ ]:
# Notebooks - a notebook is a special file (usually ,ipynb) that lets you:
# write Code
# run Code
# see output 
# Add notes equations, images, charts - all in one place



#Numpy - It is a numeric libray of python to make possible arrays in python
# Numpy is written in c which are compiled and super fast.
# this is the main reason numpy is upto 50x faster than python list.

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1,2,3.5]
a

[1, 2, 3.5]

In [5]:
np.array(a) #convert every value of a into float datatype

array([1. , 2. , 3.5])

In [6]:
l = [[1,2,3],[1,2,3],[1,2,3]]
l

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [11]:
np.array([[1,2,3],[1,2,3],[1,2,3]])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [19]:
# Array generation function

arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr2 = np.arange(1,11,2)
arr2

array([1, 3, 5, 7, 9])

In [23]:
arr = np.zeros((4,7))
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [26]:
arr = np.ones((6,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [33]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [ ]:
# Random Number Generation

arr = np.random.rand(10)
arr


# All values comes within a range of 0 to 1 this is a concept of normalization in statistics
# and when it came in range of 3 to -3 then it is standardization

array([0.48672808, 0.26680591, 0.04469299, 0.65491445, 0.89980549,
       0.78196527, 0.39680021, 0.19831857, 0.17199079, 0.50323797])

In [ ]:
arr = np.random.randn(10)     #it came in range of 3 to -3 then it is standardization
arr

array([-0.72909061, -0.29035108,  1.5328432 ,  0.93308839,  0.07582537,
        0.85704019, -0.78943836,  1.29223051,  2.25230235,  1.29502551])

In [9]:
arr = np.random.randint(10,20,12)
arr

array([14, 15, 17, 17, 15, 18, 18, 17, 14, 19, 16, 12], dtype=int32)

In [11]:
# Array Attributes

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr.shape

(3, 3)

In [13]:
arr.size

9

In [14]:
arr.dtype

dtype('int64')

In [16]:
# Array Methods

arr.min()

np.int64(1)

In [17]:
arr.max()

np.int64(9)

In [18]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0)  # it provides us the sum of column wise axis to get we use 0f

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1) # it provides us with the sum of row wise to get this we use 1 in axis

array([ 6, 15, 24])

In [22]:
arr.mean()

np.float64(5.0)

In [23]:
arr.std()

np.float64(2.581988897471611)

In [24]:
arr.argmax()

np.int64(8)

In [25]:
arr.argmin()

np.int64(0)

In [30]:
# Reshaping and resizing

arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
arr.reshape(3,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [37]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [40]:
arr = np.arange(1,41)
arr.reshape(8,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])